name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # 3. Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore BitcentFlow.Domain/BitcentFlow.Domain.csproj

    # 4. Build do projeto
    - name: Build project
      run: dotnet build BitcentFlow.Domain/BitcentFlow.Domain.csproj --configuration Release

    # 5. Gerar o número de versão baseado na data e hora de Brasília
    - name: Generate version number (Brasília Time)
      id: version
      run: |
        export TZ="America/Sao_Paulo"
        VERSION=$(date +'%Y.%m.%d-%H%M%S')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # 6. Empacotar o projeto como um pacote NuGet
    - name: Pack project
      run: dotnet pack BitcentFlow.Domain/BitcentFlow.Domain.csproj --configuration Release --no-build -p:PackageVersion=${{ env.VERSION }}

    # 7. Publicar para o GitHub Packages
    - name: Publish to GitHub Packages
      run: dotnet nuget push "BitcentFlow.Domain/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --skip-duplicate
